import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        paper: "#F6F7F9",
        ink: "#16233B",
        "ink-soft": "#495468",
        hair: "#E3E6EB",
        law: "#B7842B",
        "law-fill": "#FBF3E2",
        "law-line": "#ECD9A6",
        "law-mark": "#F6DFA6",
        "party-a": "#2E8B7A",
        "party-a-fill": "#E9F4F0",
        "party-a-line": "#BFE0D6",
        "party-b": "#2A5A8C",
        "party-b-fill": "#E9F0F8",
        "party-b-line": "#C4D6EA",
        med: "#6B4E8E",
        "med-fill": "#F0EBF7",
        "med-line": "#D7C9E8",
        risk: "#B24A3B",
        "risk-fill": "#FAECE9",
        "risk-line": "#EAC7BF",
        surface: "#F6F7F9",
        background: "#F6F7F9",
        "on-surface": "#16233B",
        "on-surface-variant": "#495468",
        "on-background": "#16233B",
        primary: "#16233B",
        "primary-container": "#16233B",
        "on-primary-container": "#FFFFFF",
        tertiary: "#B7842B",
        "tertiary-container": "#FBF3E2",
        "on-tertiary": "#8A6413",
        error: "#B24A3B",
        success: "#2E8B7A",
        outline: "#E3E6EB",
        "outline-variant": "#E3E6EB",
        "surface-container": "#FFFFFF",
        "surface-container-low": "#F6F7F9",
        "surface-container-lowest": "#F0F2F5",
        "surface-container-high": "#FFFFFF",
        "surface-container-highest": "#FFFFFF",
        "surface-variant": "#F0F2F5",
        "primary-fixed-dim": "#495468",
        card: "#FFFFFF",
      },
      spacing: {
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        gutter: "24px",
        "container-max": "1080px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "IBM Plex Sans", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "Newsreader", "serif"],
      },
      fontSize: {
        eyebrow: ["12.5px", { lineHeight: "1.4", letterSpacing: "0.14em", fontWeight: "500" }],
        "headline-md": ["19px", { lineHeight: "1.25", fontWeight: "500" }],
        "headline-lg": ["34px", { lineHeight: "1.15", fontWeight: "400" }],
        "body-sm": ["13.5px", { lineHeight: "1.55", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["11.5px", { lineHeight: "1", letterSpacing: "0.12em", fontWeight: "600" }],
        "display-lg": ["clamp(40px,7vw,72px)", { lineHeight: "1.04", letterSpacing: "-0.015em", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1080px",
        landing: "880px",
      },
      borderRadius: {
        DEFAULT: "14px",
        lg: "14px",
        xl: "14px",
        md: "10px",
        sm: "6px",
      },
      boxShadow: {
        modal: "0 18px 50px rgba(22, 35, 59, 0.22)",
        drawer: "-14px 0 40px rgba(22, 35, 59, 0.14)",
      },
    },
  },
  plugins: [],
};

export default config;
